const SESSION_STATES = {
  MAIN: 'MAIN',
  SELECT_REGION_1: 'SELECT_REGION_1',
  SELECT_REGION_2: 'SELECT_REGION_2',
  INPUT_APARTMENT: 'INPUT_APARTMENT',
  SELECT_MENU_CATEGORY: 'SELECT_MENU_CATEGORY',
  SELECT_DAY: 'SELECT_DAY',
  VIEW_MENU_DETAIL: 'VIEW_MENU_DETAIL',
  READY_TO_ORDER: 'READY_TO_ORDER',
};

module.exports = { SESSION_STATES };
